openapi: 3.0.0
info:
  title: Mahasiswa API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /mahasiswa:
    get:
      summary: Get all mahasiswa
      responses:
        '200':
          description: Success
